version: "3.7"

services:
  redis:
    image: redis:5.0.8-buster
    hostname: redis
    container_name: covid-api-redis
    networks:
      - redis-net
    volumes:
      - redis-data:/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
      - 443:443
    container_name: covid-api-app
    networks:
      - redis-net
    depends_on:
      - redis

networks:
  redis-net:

volumes:
  redis-data:
